[workspace]
git_release_enable = true
git_tag_enable = true
git_tag_name = "{{ package }}-v{{ version }}"
changelog_update = true
changelog_path = "./CHANGELOG.md"

[[package]]
name = "klattsch-core"

[[package]]
name = "klattsch-text"

[[package]]
name = "klattsch-wav"

[[package]]
name = "klattsch-wasm"
publish = false
git_release_enable = false
git_tag_enable = false
changelog_update = false
