//! Bundled phoneme banks.
//!
//! GENERATED by `tools/gen-banks.mjs` from the canonical JSON in the JS
//! engine repo (`klattsch/src/engine/banks/*.json`). Do not edit by hand;
//! re-run the generator when a bank changes.
//!
//! Phoneme order within a bank is load-bearing (it is the index space callers
//! address phonemes by), so it follows the JSON key order exactly.

use super::{params, BankSource, PhonemeEdit, PhonemeEntry};
use crate::phonemes::GlideTo;

/// Every bundled bank, in registration order: a bank always follows the one
/// it extends.
#[must_use]
pub fn sources() -> Vec<BankSource> {
    vec![klatt1980_en(), ja_mokhtari_2000(), ja_hecko_2026()]
}

/// English (Klatt 1980) (en-US).
fn klatt1980_en() -> BankSource {
    BankSource {
        name: "klatt1980-en".into(),
        display_name: "English (Klatt 1980)".into(),
        language: Some("en-US".into()),
        license: Some("MIT".into()),
        source: Some("Klatt, D.H. (1980). \"Software for a cascade/parallel formant synthesizer.\" J. Acoust. Soc. Am. 67(3), Tables II (vowels) and III (consonants). Bandwidths and frequencies are verbatim from Klatt; amplitudes are approximated for our 3-formant parallel synth (Klatt uses six formants plus a bypass path for fricative spectra). Where Klatt places fricative energy in A3-A6 (~3-5 kHz parallel formants), we move our F3 channel up into that band to capture the hiss.".into()),
        extends: None,
        edits: vec![
        PhonemeEdit::Set(PhonemeEntry {
            name: "IY".into(),
            params: params(1.0, 310.0, 2020.0, 2960.0, 45.0, 200.0, 400.0, 1.0, 0.9, 0.7, Some(GlideTo { f1: 290.0, f2: 2070.0, f3: 2960.0 }), false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "IH".into(),
            params: params(1.0, 400.0, 1800.0, 2570.0, 50.0, 100.0, 140.0, 1.0, 0.9, 0.7, Some(GlideTo { f1: 470.0, f2: 1600.0, f3: 2600.0 }), false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "EH".into(),
            params: params(1.0, 530.0, 1680.0, 2500.0, 60.0, 90.0, 200.0, 1.0, 0.9, 0.7, Some(GlideTo { f1: 620.0, f2: 1530.0, f3: 2530.0 }), false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "AE".into(),
            params: params(1.0, 620.0, 1660.0, 2430.0, 70.0, 150.0, 320.0, 1.0, 0.9, 0.7, Some(GlideTo { f1: 650.0, f2: 1490.0, f3: 2470.0 }), false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "AA".into(),
            params: params(1.0, 700.0, 1220.0, 2600.0, 130.0, 70.0, 160.0, 1.0, 0.9, 0.7, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "AO".into(),
            params: params(1.0, 600.0, 990.0, 2570.0, 90.0, 100.0, 80.0, 1.0, 0.9, 0.7, Some(GlideTo { f1: 630.0, f2: 1040.0, f3: 2600.0 }), false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "AH".into(),
            params: params(1.0, 620.0, 1220.0, 2550.0, 80.0, 50.0, 140.0, 1.0, 0.9, 0.7, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "UH".into(),
            params: params(1.0, 450.0, 1100.0, 2350.0, 80.0, 100.0, 80.0, 1.0, 0.9, 0.7, Some(GlideTo { f1: 500.0, f2: 1180.0, f3: 2390.0 }), false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "UW".into(),
            params: params(1.0, 350.0, 1250.0, 2200.0, 65.0, 110.0, 140.0, 1.0, 0.9, 0.7, Some(GlideTo { f1: 320.0, f2: 900.0, f3: 2200.0 }), false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "ER".into(),
            params: params(1.0, 470.0, 1270.0, 1540.0, 100.0, 60.0, 110.0, 1.0, 0.9, 0.7, Some(GlideTo { f1: 420.0, f2: 1310.0, f3: 1540.0 }), false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "AY".into(),
            params: params(1.0, 660.0, 1200.0, 2550.0, 100.0, 70.0, 200.0, 1.0, 0.9, 0.7, Some(GlideTo { f1: 400.0, f2: 1880.0, f3: 2500.0 }), false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "AW".into(),
            params: params(1.0, 640.0, 1230.0, 2550.0, 80.0, 70.0, 140.0, 1.0, 0.9, 0.7, Some(GlideTo { f1: 420.0, f2: 940.0, f3: 2350.0 }), false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "EY".into(),
            params: params(1.0, 480.0, 1720.0, 2520.0, 70.0, 100.0, 200.0, 1.0, 0.9, 0.7, Some(GlideTo { f1: 330.0, f2: 2020.0, f3: 2600.0 }), false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "OW".into(),
            params: params(1.0, 540.0, 1100.0, 2300.0, 80.0, 70.0, 70.0, 1.0, 0.9, 0.7, Some(GlideTo { f1: 450.0, f2: 900.0, f3: 2300.0 }), false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "OY".into(),
            params: params(1.0, 550.0, 960.0, 2400.0, 80.0, 50.0, 130.0, 1.0, 0.9, 0.7, Some(GlideTo { f1: 360.0, f2: 1820.0, f3: 2450.0 }), false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "W".into(),
            params: params(1.0, 290.0, 610.0, 2150.0, 50.0, 80.0, 60.0, 0.8, 0.7, 0.5, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "Y".into(),
            params: params(1.0, 260.0, 2070.0, 3020.0, 40.0, 250.0, 500.0, 0.8, 0.7, 0.5, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "R".into(),
            params: params(1.0, 310.0, 1060.0, 1380.0, 70.0, 100.0, 120.0, 0.8, 0.7, 0.5, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "L".into(),
            params: params(1.0, 310.0, 1050.0, 2880.0, 50.0, 100.0, 280.0, 0.8, 0.7, 0.5, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "M".into(),
            params: params(1.0, 270.0, 1270.0, 2130.0, 40.0, 200.0, 200.0, 0.7, 0.18, 0.1, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "N".into(),
            params: params(1.0, 270.0, 1340.0, 2470.0, 40.0, 300.0, 300.0, 0.7, 0.2, 0.12, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "NG".into(),
            params: params(1.0, 270.0, 2000.0, 2700.0, 40.0, 300.0, 300.0, 0.7, 0.2, 0.12, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "F".into(),
            params: params(0.0, 340.0, 1100.0, 2080.0, 200.0, 200.0, 1000.0, 0.0, 0.1, 0.15, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "TH".into(),
            params: params(0.0, 320.0, 1290.0, 2540.0, 200.0, 200.0, 1000.0, 0.0, 0.08, 0.18, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "S".into(),
            params: params(0.0, 320.0, 1390.0, 5500.0, 200.0, 200.0, 1000.0, 0.0, 0.0, 0.95, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "SH".into(),
            params: params(0.0, 300.0, 1840.0, 2750.0, 200.0, 200.0, 1000.0, 0.0, 0.55, 0.65, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "V".into(),
            params: params(0.45, 220.0, 1100.0, 2080.0, 80.0, 100.0, 800.0, 0.4, 0.12, 0.18, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "DH".into(),
            params: params(0.45, 270.0, 1290.0, 2540.0, 80.0, 100.0, 800.0, 0.4, 0.1, 0.2, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "Z".into(),
            params: params(0.45, 240.0, 1390.0, 5500.0, 80.0, 100.0, 800.0, 0.4, 0.0, 0.65, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "ZH".into(),
            params: params(0.45, 270.0, 1840.0, 2750.0, 80.0, 100.0, 800.0, 0.4, 0.45, 0.55, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "HH".into(),
            params: params(0.0, 500.0, 1500.0, 2500.0, 300.0, 200.0, 300.0, 0.4, 0.4, 0.3, None, false),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "P".into(),
            params: params(0.0, 400.0, 1100.0, 2150.0, 300.0, 150.0, 220.0, 0.1, 0.2, 0.25, None, true),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "B".into(),
            params: params(0.6, 200.0, 1100.0, 2150.0, 60.0, 110.0, 130.0, 0.5, 0.2, 0.2, None, true),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "T".into(),
            params: params(0.0, 400.0, 1600.0, 2600.0, 300.0, 120.0, 250.0, 0.0, 0.3, 0.55, None, true),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "D".into(),
            params: params(0.6, 200.0, 1600.0, 2600.0, 60.0, 100.0, 170.0, 0.5, 0.4, 0.5, None, true),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "K".into(),
            params: params(0.0, 300.0, 1990.0, 2850.0, 250.0, 160.0, 330.0, 0.0, 0.5, 0.4, None, true),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "G".into(),
            params: params(0.6, 200.0, 1990.0, 2850.0, 60.0, 150.0, 280.0, 0.5, 0.5, 0.4, None, true),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "CH".into(),
            params: params(0.0, 350.0, 1800.0, 2820.0, 200.0, 90.0, 300.0, 0.0, 0.4, 0.55, None, true),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "JH".into(),
            params: params(0.5, 260.0, 1800.0, 2820.0, 60.0, 80.0, 270.0, 0.4, 0.4, 0.5, None, true),
            ipa: None,
            example: None,
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "_".into(),
            params: params(0.0, 500.0, 1500.0, 2500.0, 80.0, 120.0, 160.0, 0.0, 0.0, 0.0, None, false),
            ipa: None,
            example: None,
        }),
        ],
    }
}

/// Japanese (Mokhtari & Tanaka 2000) (ja-JP).
fn ja_mokhtari_2000() -> BankSource {
    BankSource {
        name: "ja-mokhtari-2000".into(),
        display_name: "Japanese (Mokhtari & Tanaka 2000)".into(),
        language: Some("ja-JP".into()),
        license: Some("MIT".into()),
        source: Some("\"A Corpus of Japanese Vowel Formant Patterns.\" Bulletin of the Electrotechnical Laboratory (ETL), Vol. 64, Special Issue, 57-66. Raw data file: https://web.archive.org/web/20240811224814/https://isd.pu-toyama.ac.jp/~parham/documents/formantsETL/MokhtariTanaka2000_ETLformantdata.txt . Frequencies and bandwidths rounded to the nearest Hz. Mokhtari & Tanaka covers vowels only; the alveolar tap (DX) is reproduced from the ja-hecko-2026 bank with credit to .hecko on the klattsch Discord.".into()),
        extends: Some("klatt1980-en".into()),
        edits: vec![
        PhonemeEdit::Set(PhonemeEntry {
            name: "I".into(),
            params: params(1.0, 298.0, 2083.0, 2954.0, 67.0, 130.0, 145.0, 1.0, 0.9, 0.7, None, false),
            ipa: Some("i".into()),
            example: Some("[i]ru".into()),
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "E".into(),
            params: params(1.0, 480.0, 1857.0, 2437.0, 65.0, 97.0, 257.0, 1.0, 0.9, 0.7, None, false),
            ipa: Some("e̞".into()),
            example: Some("[e]ki".into()),
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "A".into(),
            params: params(1.0, 744.0, 1240.0, 2426.0, 182.0, 117.0, 222.0, 1.0, 0.9, 0.7, None, false),
            ipa: Some("ä".into()),
            example: Some("[a]ru".into()),
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "O".into(),
            params: params(1.0, 460.0, 857.0, 2405.0, 61.0, 114.0, 134.0, 1.0, 0.9, 0.7, None, false),
            ipa: Some("o̞".into()),
            example: Some("[o]ni".into()),
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "U".into(),
            params: params(1.0, 355.0, 1282.0, 2233.0, 55.0, 129.0, 135.0, 1.0, 0.9, 0.7, None, false),
            ipa: Some("ɯᵝ".into()),
            example: Some("[u]nagi".into()),
        }),
        PhonemeEdit::Set(PhonemeEntry {
            name: "DX".into(),
            params: params(0.6, 255.0, 1325.0, 2740.0, 55.0, 100.0, 225.0, 0.65, 0.55, 0.5, None, true),
            ipa: Some("ɾ".into()),
            example: Some("koko[r]o".into()),
        }),
        ],
    }
}

/// Japanese (.hecko, 2026) (ja-JP).
fn ja_hecko_2026() -> BankSource {
    BankSource {
        name: "ja-hecko-2026".into(),
        display_name: "Japanese (.hecko, 2026)".into(),
        language: Some("ja-JP".into()),
        license: Some("MIT".into()),
        source: Some(
            "Vowel formant values contributed by .hecko on the klattsch Discord, May 2026.".into(),
        ),
        extends: Some("klatt1980-en".into()),
        edits: vec![
            PhonemeEdit::Set(PhonemeEntry {
                name: "I".into(),
                params: params(
                    1.0, 350.0, 2000.0, 3000.0, 60.0, 130.0, 140.0, 1.0, 0.9, 0.7, None, false,
                ),
                ipa: Some("i".into()),
                example: Some("[i]ru".into()),
            }),
            PhonemeEdit::Set(PhonemeEntry {
                name: "E".into(),
                params: params(
                    1.0, 500.0, 1700.0, 2300.0, 60.0, 100.0, 250.0, 1.0, 0.9, 0.7, None, false,
                ),
                ipa: Some("e̞".into()),
                example: Some("[e]ki".into()),
            }),
            PhonemeEdit::Set(PhonemeEntry {
                name: "A".into(),
                params: params(
                    1.0, 750.0, 1250.0, 2250.0, 180.0, 110.0, 220.0, 1.0, 0.9, 0.7, None, false,
                ),
                ipa: Some("ä".into()),
                example: Some("[a]ru".into()),
            }),
            PhonemeEdit::Set(PhonemeEntry {
                name: "O".into(),
                params: params(
                    1.0, 500.0, 850.0, 2250.0, 60.0, 110.0, 130.0, 1.0, 0.9, 0.7, None, false,
                ),
                ipa: Some("o̞".into()),
                example: Some("[o]ni".into()),
            }),
            PhonemeEdit::Set(PhonemeEntry {
                name: "U".into(),
                params: params(
                    1.0, 450.0, 1250.0, 2150.0, 50.0, 120.0, 130.0, 1.0, 0.9, 0.7, None, false,
                ),
                ipa: Some("ɯᵝ".into()),
                example: Some("[u]nagi".into()),
            }),
            PhonemeEdit::Set(PhonemeEntry {
                name: "DX".into(),
                params: params(
                    0.6, 255.0, 1325.0, 2740.0, 55.0, 100.0, 225.0, 0.65, 0.55, 0.5, None, true,
                ),
                ipa: Some("ɾ".into()),
                example: Some("koko[r]o".into()),
            }),
        ],
    }
}
