#!/usr/bin/env node
// Generates crates/klattsch-core/src/banks/bundled.rs from the canonical
// phoneme bank JSON in the JS engine repo.
//
//   node tools/gen-banks.mjs [path/to/klattsch/src/engine/banks]
//
// The JS banks are the source of truth for phoneme data across every port, so
// this file is generated rather than transcribed. Re-run it when a bank
// changes and commit the result.

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const banksDir = resolve(
  process.argv[2] ?? join(here, '..', '..', 'klattsch', 'src', 'engine', 'banks'),
);
const outPath = join(here, '..', 'crates', 'klattsch-core', 'src', 'banks', 'bundled.rs');

// Registration order matters: a bank must be registered after the bank it
// extends, and the order is the order `BankRegistry::list()` reports.
const ORDER = ['klatt1980-en', 'ja-mokhtari-2000', 'ja-hecko-2026'];

const files = readdirSync(banksDir).filter((f) => f.endsWith('.json'));
const banks = new Map();
for (const file of files) {
  const bank = JSON.parse(readFileSync(join(banksDir, file), 'utf8'));
  if (bank.schemaVersion !== 1) {
    throw new Error(`${file}: unsupported schemaVersion ${bank.schemaVersion}`);
  }
  banks.set(bank.name, bank);
}
for (const name of ORDER) {
  if (!banks.has(name)) throw new Error(`missing bank: ${name}`);
}
const extra = [...banks.keys()].filter((n) => !ORDER.includes(n));
if (extra.length) {
  throw new Error(`unlisted banks (add to ORDER): ${extra.join(', ')}`);
}

const rustStr = (s) => JSON.stringify(s);
const opt = (s) => (s == null ? 'None' : `Some(${rustStr(s)}.into())`);
// Every numeric field is emitted with a decimal point so the literals are f32
// without a suffix and read as the JSON does.
const f32 = (n) => {
  if (!Number.isFinite(n)) throw new Error(`non-finite value: ${n}`);
  return Number.isInteger(n) ? `${n}.0` : `${n}`;
};

const ident = (name) => name.replace(/[^A-Za-z0-9]/g, '_').toUpperCase();

function emitEdit(code, entry) {
  if (entry === null) {
    return `        PhonemeEdit::Remove(${rustStr(code)}.into()),`;
  }
  const p = entry;
  for (const k of ['voicing', 'F1', 'F2', 'F3', 'BW1', 'BW2', 'BW3', 'A1', 'A2', 'A3']) {
    if (typeof p[k] !== 'number') throw new Error(`${code}: missing ${k}`);
  }
  const glide = p.glideTo
    ? `Some(GlideTo { f1: ${f32(p.glideTo.F1)}, f2: ${f32(p.glideTo.F2)}, f3: ${f32(p.glideTo.F3)} })`
    : 'None';
  const params = [
    f32(p.voicing),
    f32(p.F1),
    f32(p.F2),
    f32(p.F3),
    f32(p.BW1),
    f32(p.BW2),
    f32(p.BW3),
    f32(p.A1),
    f32(p.A2),
    f32(p.A3),
    glide,
    p.isStop === true ? 'true' : 'false',
  ].join(', ');
  return [
    '        PhonemeEdit::Set(PhonemeEntry {',
    `            name: ${rustStr(code)}.into(),`,
    `            params: params(${params}),`,
    `            ipa: ${opt(p.ipa)},`,
    `            example: ${opt(p.example)},`,
    '        }),',
  ].join('\n');
}

function emitBank(bank) {
  const edits = Object.entries(bank.phonemes ?? {})
    .map(([code, entry]) => emitEdit(code, entry))
    .join('\n');
  return [
    `/// ${bank.displayName}${bank.language ? ` (${bank.language})` : ''}.`,
    `fn ${ident(bank.name).toLowerCase()}() -> BankSource {`,
    '    BankSource {',
    `        name: ${rustStr(bank.name)}.into(),`,
    `        display_name: ${rustStr(bank.displayName ?? bank.name)}.into(),`,
    `        language: ${opt(bank.language)},`,
    `        license: ${opt(bank.license)},`,
    `        source: ${opt(bank.source)},`,
    `        extends: ${opt(bank.extends)},`,
    '        edits: vec![',
    edits,
    '        ],',
    '    }',
    '}',
  ].join('\n');
}

const bodies = ORDER.map((name) => emitBank(banks.get(name))).join('\n\n');
const calls = ORDER.map((name) => `        ${ident(name).toLowerCase()}(),`).join('\n');

const out = `//! Bundled phoneme banks.
//!
//! GENERATED by \`tools/gen-banks.mjs\` from the canonical JSON in the JS
//! engine repo (\`klattsch/src/engine/banks/*.json\`). Do not edit by hand;
//! re-run the generator when a bank changes.
//!
//! Phoneme order within a bank is load-bearing (it is the index space callers
//! address phonemes by), so it follows the JSON key order exactly.

use super::{params, BankSource, PhonemeEdit, PhonemeEntry};
use crate::phonemes::GlideTo;

/// Every bundled bank, in registration order: a bank always follows the one
/// it extends.
#[must_use]
pub fn sources() -> Vec<BankSource> {
    vec![
${calls}
    ]
}

${bodies}
`;

writeFileSync(outPath, out);
const counts = ORDER.map((n) => `${n}=${Object.keys(banks.get(n).phonemes ?? {}).length}`);
console.log(`wrote ${outPath}`);
console.log(`banks: ${counts.join(' ')}`);
